[package]
name = "nikola"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27"
wgpu = "0.14"
# env_logger = "0.9"
# log = "0.4"
pollster = "0.2.5"
bytemuck = { version = "1.12.3", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
num-traits = "0.2.15"
imgui = "0.9.0"
imgui-wgpu = "0.21.0"
imgui-winit-support = "0.9.0"
